fix(snake workflow): test without output parameters

diff --git a/.github/workflows/snake.yml b/.github/workflows/snake.yml
--- a/.github/workflows/snake.yml
+++ b/.github/workflows/snake.yml
@@ -19,12 +19,15 @@ jobs:
         uses: platane/snk@main
         with:
           github_user_name: ${{ github.actor }}
-          args: --output dist/github-contribution-grid-snake.svg
+      - name: List files
+        run: |
+          ls -la
+          ls -la dist/ 2>/dev/null || echo "dist not found"
       - name: Commit and push
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-          git add dist/github-contribution-grid-snake.svg
+          git add dist/
           git diff --quiet && exit 0
           git commit -m "Update snake SVG [skip ci]"
           git push
